### ISSUE TITLE
is there any support for male/female version

### ISSUE THREAD

**Issue by sunil-paxcel** [lino-levan/better-node-gtts#1]

**Comment by lino-levan** [comment]
I did not see this issue somehow.... We are using the google text to speech provided by google translate. This means that it is free which is good (otherwise we'd need google api credits), but it also means we are limited to the female voice.

Adding a male voice is out of scope for this project since we're not actually using the official tts api. I hope you understand. You could always transform the voice to _sound_ male by messing with the pitch and speed but that's a little janky.
